### ISSUE TITLE
Tar files in npm registry have incorrectly encoded test filenames

### ISSUE THREAD

**Issue by tomhughes** [mapbox/node-zipfile#29]
The files in the test directory with unicode names are using codepoints which combine the base character and accent in a single codepoint when fetched from git, which matches what the test scripts expect.

When the tar ball from the npm registry is used however the filenames have separate combining characters for the accents, which mean the tests fail because the names do not match.

As an example, consider `tests/data/Clément` which should be encoded as:

````
Cl<U+E9>ment
````

but in the npm tarball is encoded as:

````
Cle<U+301>ment
````

**Comment by springmeyer** [comment]
not seen this problem for a while I'm assuming something was fixed upstream in npm.
