### ISSUE TITLE
Zip archive inconsistent

### ISSUE THREAD

**Issue by cappelaere** [mapbox/node-zipfile#44]
Dane,

I hate doing this to you but I went back to the Mac running 10.9.1 and I am encountering that problem on the first file I am trying to inspect.

> var zipfile = require('zipfile')
> filename = "/home/node/shared/production/proddata/radarsat/l1g/zips/RS2_OK16630_PK174790_DK165236_MF1_20101106_230031_HH_SGF.zip"
> var zf = new zipfile.ZipFile(filename);
> Error: cannot open file: /home/node/shared/production/proddata/radarsat/l1g/zips/RS2_OK16630_PK174790_DK165236_MF1_20101106_230031_HH_SGF.zip error: Zip archive inconsistent

```
at repl:1:10
at REPLServer.self.eval (repl.js:110:21)
at repl.js:249:20
at REPLServer.self.eval (repl.js:122:7)
at Interface.<anonymous> (repl.js:239:12)
at Interface.EventEmitter.emit (events.js:95:17)
at Interface._onLine (readline.js:202:10)
at Interface._line (readline.js:531:8)
at Interface._ttyWrite (readline.js:760:14)
at ReadStream.onkeypress (readline.js:99:10)
```

Note:  The file exists.  It can be unzipped fine by Finder and  Adm-zip.  Just wanted to let you know.  I am not sure where to go from there...
File is 141MB
Thanks again.
Pat.

**Comment by nbrustein** [comment]
I'm getting this error with a zipfile that passes `zip --test`, and can be opened in iBooks.  Using version  `0.5.12`.

I don't want to paste the file here, since it is copyrighted, but I can send it privately if that's helpful.

Any idea of something I can try?

**Comment by springmeyer** [comment]
@nbrustein this module is not actively developed anymore. If you want to see something fixed, I think you'll need to do the work yourself to fix it.
