### ISSUE TITLE
Shrinkwrapping fails with new versions of NPM

### ISSUE THREAD

**Issue by keithamus** [mapbox/node-zipfile#51]
Please see this issue: https://github.com/npm/npm/issues/6655

It seems that because zipfile uses semver, combined with pre-release versions, that shrinkwrapping in npm 2 fails. The best way to resolve this, it seems, is to [bundle node-pre-gyp with the latest version of npm](https://github.com/npm/npm/issues/6655#issuecomment-61977474).

**Comment by springmeyer** [comment]
This will be fixed by unbundling node-pre-gyp, which is done in https://github.com/mapbox/node-zipfile/commit/6be827e212cf8886f594e3dc1cf0ef82c307a2f0
