### ISSUE TITLE
Building in Windows x64 Failing

### ISSUE THREAD

**Issue by BHare1985** [mapbox/node-zipfile#58]
I am sure you are aware of this, because a google of my errors return this:

https://ci.appveyor.com/project/Mapbox/node-zipfile/build/1.0.58

Specifically: https://ci.appveyor.com/project/Mapbox/node-zipfile/build/1.0.58/job/uh7jc9h0jk47fhcn

Where I am trying to build on x64 with NodeJS v0.12 with 2013 VS (using --msvs_version=2013)

Here is my debug log: https://www.dropbox.com/s/xkloztkj47ga7sp/npm-debug.log?dl=0
and my cmd output: https://www.dropbox.com/s/dnbmnjjqcfdl9gp/2015-05-30_18-52-32.txt?dl=0

I am using the lastest commit at the time ( https://github.com/mapbox/node-zipfile/tree/6e72a48dd3656c94f63daad77aafac684d501385 ).

Just letting you there is actually a windows user who wants to use this module (or more accurately trying to use it with millstone)

**Comment by BergWerkGIS** [comment]
@BHare1985 
Compiles fine for me locally with node v0.10.33.
Newer versions seem to fail.
Which is interesting, because they used to work before: https://ci.appveyor.com/project/Mapbox/node-zipfile/build/1.0.45

Investigating ...

**Comment by BergWerkGIS** [comment]
@BHare1985 

Please try this from a x64 native command prompt.
It worked for me with latest `node v0.12.4` and VS2013.

Save this patch as a file, e.g. `win.diff` (be careful, that you have an empty line at the end of the file):

```diff
diff --git a/deps/zlib/zconf.h b/deps/zlib/zconf.h
index b0e17bb..d3b0a88 100644
--- a/deps/zlib/zconf.h
+++ b/deps/zlib/zconf.h
@@ -9,8 +9,9 @@
 #define ZCONF_H
 
 /* This include does prefixing as below, but with an updated set of names */
+#if !defined(_WIN32)
 #include "mozzconf.h"
-
+#endif
 /*
  * If you *really* need a unique prefix for all types and library functions,
  * compile with -DZ_PREFIX. The "standard" zlib should be compiled without it.
    
```

Then in the directory, where you saved the patch:
```
git clone https://github.com/mapbox/node-zipfile.git
cd node-zipfile
git apply ..\win.diff
npm install --build-from-source --msvs_version=2013
npm test
```

Does it work?

**Comment by BHare1985** [comment]
fatal: corrupt patch at line 7

Reading up on why that could be now. Never applied diffs before.

**Comment by BHare1985** [comment]
Happy to report that after applying the patch that it installed success full and all tests passed. This can be closed when you are ready.

**Comment by BergWerkGIS** [comment]
@BHare1985 Thanks for testing.

I've applied the change to this repo. 
No manual patching necessary anymore.

All green on AppVeyor, too:
https://ci.appveyor.com/project/Mapbox/node-zipfile/build/1.0.62
