### ISSUE TITLE
A dynamic link library initialization routine failed

### ISSUE THREAD

**Issue by amsoell** [mapbox/node-zipfile#67]
Hoping you can help me sort this one out—I'm using this in an Electron application, and it's working fine on OS X. When I try to run my project on a Windows 10 machine, I get the following error:

![](http://i.imgur.com/ef09fj4.png)

```
App threw an error when running [Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\IEUser\Desktop\outputstudio_desktop\src\node_modules\zipfile\lib\binding\node-v47-win32-ia32\zipfile.node]
```

And line 22 of index.js, as referenced in the error, is just pulling in zipfile into the project:

```
var zipfile = require('zipfile');
```

This is on a Windows 10 machine running in VirtualBox—if there's any more information that might help I'm happy to pass that along.

**Comment by BergWerkGIS** [comment]
You could try these steps (https://github.com/mapnik/node-mapnik/wiki/Troubleshooting#the-specified-module-cannot-be-found) passing in `zipfile.node` and see if you get any additional information.

Since you are using 32bit node ("node-v47-win32-**ia32**") you would have to also use 32bit Python.

**Comment by springmeyer** [comment]
You are trying to use the binary for node in electron. They are not compatible. You need to rebuild for electron. See the https://github.com/electron/electron-rebuild project.
