### ISSUE TITLE
Question: release 0.5.10

### ISSUE THREAD

**Issue by dgaubert** [mapbox/node-zipfile#71]
When do you plan to release 0.5.10?

By the way, I've tried to install current master on Node v6 LTS but tests show:

```
(node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
(node) and will stop working in the next major release.
```

**Comment by dgaubert** [comment]
Is there any update here?

**Comment by springmeyer** [comment]
thanks for the ping v0.5.10 is now published.
