### ISSUE TITLE
Missing windows binary for node 8

### ISSUE THREAD

**Issue by jingsam** [mapbox/node-zipfile#81]
Seems the fellowing binary is missing:
```
https://mapbox-node-binary.s3.amazonaws.com/zipfile/v0.5.12/node-v57-win32-x64.tar.gz
```

**Comment by springmeyer** [comment]
duplicate of #80

**Comment by springmeyer** [comment]
Actually sorry, #80 is just about node v10. This should be fixed as long at https://ci.appveyor.com/project/Mapbox/node-zipfile/build/1.0.158 goes green.
